apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: task-queue-api-pdb
  namespace: {{ include "task-queue.namespace" . }}
  labels:
    app: task-queue-api
spec:
  minAvailable: {{ .Values.pdb.api.minAvailable | default 1 }}
  selector:
    matchLabels:
      app: task-queue-api
