apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-queue-api
  namespace: {{ include "task-queue.namespace" . }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-queue-worker
  namespace: {{ include "task-queue.namespace" . }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-queue-scheduler
  namespace: {{ include "task-queue.namespace" . }}
automountServiceAccountToken: false
