version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: ../..
      dockerfile: deploy/local/docker/api.Dockerfile
    environment:
      PORT: "8080"
      REDIS_HOST: redis:6379
      REDIS_DB: "0"
      REDIS_PASSWORD: ""
      STORE_BACKEND: redis
      API_KEY: secret-api-key
    ports:
      - "8080:8080"
    depends_on:
      - redis

  worker:
    build:
      context: ../..
      dockerfile: deploy/local/docker/worker.Dockerfile
    environment:
      REDIS_HOST: redis:6379
      REDIS_DB: "0"
      REDIS_PASSWORD: ""
      WORKER_POOL_SIZE: "50"
    depends_on:
      - redis

  scheduler:
    build:
      context: ../..
      dockerfile: deploy/local/docker/scheduler.Dockerfile
    command: ["./scheduler"]
    environment:
      REDIS_HOST: redis:6379
      REDIS_DB: "0"
      REDIS_PASSWORD: ""
    depends_on:
      - redis
