version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.54.0
    container_name: task-queue-prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - task-queue-net

  grafana:
    image: grafana/grafana:11.1.0
    container_name: task-queue-grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ../grafana/provisioning/:/etc/grafana/provisioning/
      - ../grafana/dashboard.json:/var/lib/grafana/dashboards/task-queue.json
    networks:
      - task-queue-net
    depends_on:
      - prometheus

volumes:
  prometheus-data:
  grafana-data:

networks:
  task-queue-net:
    name: task-queue-monitoring
